Threaded chunk loaders
BenjaTK/Gaea pull request #116
Opened 2024-05-30 15:42 UTC by cullumi

Implemented some threaded chunk loaders (wrappers for the non-threaded ones). Mostly just intended to get the bulk of the loading process off of the main thread.

2024-05-30 15:44 UTC, cullumi commented
There's still some stuttering that happens, but I haven't quite narrowed down the cause.

2024-05-30 16:38 UTC, BenjaTK commented on addons/gaea/generators/2D/chunk_aware_generator_2d.gd
> +	(func(): chunk_erased.emit(chunk_position)).call_deferred() # deferred for threadability
I think you can just do something like `chunk_erased.emit.call_deferred(chunk_position)`, instead of having to create a lambda. Would work the same probably just easier to read.

2024-05-31 00:09 UTC, cullumi commented on addons/gaea/generators/2D/chunk_aware_generator_2d.gd
> +	(func(): chunk_erased.emit(chunk_position)).call_deferred() # deferred for threadability
I thought the same thing, but surprisingly enough, you actually can't. The reason why is that Signals aren't Objects, so therefore methods called on them cannot be made into Callables. I found the recommendation of using lambdas in the Callable documentation iirc.

2024-05-31 01:39 UTC, cullumi commented
> There's still some stuttering that happens, but I haven't quite narrowed down the cause. Pretty sure lag spikes are much shorter in length than when I started, though.

I figured out that the stuttering came from the Tilemap and Gridmap GaeaRenderers. I threaded them too and there is hardly any lag now. You do technically run a greater risk of falling into pits and the like, though there are ways around that I'm pretty sure.

The rate at which it renders can be improved by running each render task in parallel (currently it waits for one to complete, then moves on to the next in a queue).

2024-05-31 02:20 UTC, cullumi commented
Made is so that the Threaded Gridmap and Tilemap renderers can render chunks in parallel.

Next, I need to make them gracefully handle "misses" that I suspect are resulting from trying to un-render chunks that have already been or are being un-rendered.

2024-05-31 03:01 UTC, cullumi commented
Fixed the errors I was encountering. It wasn't a logical error ("misses") after all, it was just that there were still a few method calls to the Tilemap and Gridmap that needed to be deferred. The error is gone now and the crashes that they were causes have stopped as well.

Tbh this is pretty much ready to go at this point.

2024-06-05 15:12 UTC, BenjaTK requested changes
Ngl this brings tears to my eyes, it's beautiful. 3D is so much smoother now. This could actually push us to the 1.0 release and to upload it to the Godot Asset Library.

2024-06-05 15:12 UTC, BenjaTK commented on addons/gaea/renderers/2D/threaded_tilemap_gaea_renderer.gd
> +@export var max_running:int = 1
Could you add a description to this that says that setting it to -1 will uncap it? And maybe make it an `export_range` with a minimum of -1 and an uncapped max.

2024-06-05 15:12 UTC, BenjaTK commented on addons/gaea/renderers/3D/threaded_gridmap_gaea_renderer.gd
> +@export var max_running:int = 1
Same as the Tilemap one.

2024-06-05 15:12 UTC, BenjaTK commented on addons/gaea/others/threaded_chunk_loader_2d.gd
And would it be possible to have multiple tasks in ChunkLoaders like how it is in the renderers? You can still see the chunks loading especially in 3D.

2024-06-06 14:35 UTC, cullumi commented on addons/gaea/others/threaded_chunk_loader_2d.gd
The answer is yes! But also it'll take digging into the details a bit more and breaking up the original _update_loading function in a way that can be parallelized. Sooo... probably best saved for a separate PR tbh.

2024-06-06 15:11 UTC, BenjaTK approved these changes

2024-06-06 15:11 UTC, merged