changed the way the noise generator accepts data
BenjaTK/Gaea pull request #88
Opened 2023-12-25 13:28 UTC by DaviD4Chirino

I changed from a dictionary to an Array of a custom resource that includes a threshold, TileInfo and a title so one can see what tile its generating.

It skips the sorting.

Also i use [GDFormat](https://www.gdquest.com/tutorial/godot/gdscript/gdscript-formatter/), a godot auto formatter so spacing might have changed

2023-12-25 13:30 UTC, DaviD4Chirino commented
Also its my first time adding anithing into another person work, but the way to use the noise generator by making a dictionary with an uncheangeable key it stressed me so...

2023-12-28 14:54 UTC, BenjaTK commented on project.godot
This change should be removed as it would probably cause conflicts.

2023-12-28 14:59 UTC, BenjaTK requested changes
This looks great! Well done! This will definitely make it easier. Another thing we could add is making the threshold have a max and the minimum (either as the default or as an optional change).

2023-12-28 14:59 UTC, BenjaTK commented on project.godot
This change should be removed as it could cause conflicts.

2023-12-28 14:59 UTC, BenjaTK commented on addons/gaea/generators/2D/noise_generator/noise_generator_data.gd
> +@export var title: String
I think the title property should change the `resource_name` of the data. I did the same for TileInfo I think.

2023-12-28 14:59 UTC, BenjaTK commented on addons/gaea/generators/2D/noise_generator/noise_generator_data.gd
> +##Intended only for organizing
Also, just for consistency, please add 2 empty lines after the class_name and reverse the order of the 2 first lines like the other scripts. Also adding a small description to the class and variables would be nice.

2023-12-28 14:59 UTC, BenjaTK commented on scenes/demos/noise/noise_demo.tscn
Updating this demo to match the other one would also be nice, shouldn't be hard.

2023-12-28 14:59 UTC, BenjaTK commented
Also I'm so sorry for being so late.

2023-12-28 20:47 UTC, DaviD4Chirino commented on project.godot
I tried to downgrade it into godot 4.1 but it uses syntax from 4.2, so i assumed you mean the gl_compatibility so i changed that, let me know if the version causes problems.

2023-12-28 21:25 UTC, BenjaTK reviewed
Everything else LGTM!

2023-12-28 21:25 UTC, BenjaTK commented on addons/gaea/generators/2D/noise_generator/noise_generator_data.gd
> +## the noise it will place the [param tile] there
I think this could be changed to "If the noise value at a cell is lower than [param threshold], [param tile] will be placed.

2023-12-28 21:25 UTC, BenjaTK commented on addons/gaea/generators/2D/noise_generator/noise_generator_data.gd
> +@export var tile: TileInfo = TileInfo.new()
The default value shouldn't be TileInfo.new(), it should be null.

2023-12-28 21:33 UTC, DaviD4Chirino commented on addons/gaea/generators/2D/noise_generator/noise_generator_data.gd
> +## the noise it will place the [param tile] there
i just implemented the ranged thresholds and im wrapping up, i have a group named thresholds with a min and max range, how about you check this first? 
```
## To allow for a range of thresholds
## Also min and max have a setter that prevents min from being greater than max and vice versa
@export_group("Thresholds")

## The minimum threshold
@export_range(-1.0, 1.0) var min: float = -1.0 : 
	set(value):
		min = value
		if min > max:
			max = min

## The maximum threshold
@export_range(-1.0, 1.0) var max: float = 1.0 : 
	set(value):
		max = value
		if max < min:
			min = max
```

2023-12-28 21:45 UTC, BenjaTK commented on addons/gaea/generators/2D/noise_generator/noise_generator_data.gd
> +## the noise it will place the [param tile] there
Looks great! Do groups have tooltips? I don't think they do.

2023-12-28 21:45 UTC, BenjaTK commented on addons/gaea/generators/2D/noise_generator/noise_generator_data.gd
> +## the noise it will place the [param tile] there
I would also recommend renaming it to threshold_min and threshold_max and doing @export_group("Thresholds", "threshold_"), just for clarity.

2023-12-28 21:50 UTC, DaviD4Chirino commented on addons/gaea/generators/2D/noise_generator/noise_generator_data.gd
> +## the noise it will place the [param tile] there
Did not know about that, actually

2023-12-28 22:38 UTC, BenjaTK approved these changes
LGTM! Just need to solve those conflicts
![image](https://github.com/BenjaTK/Gaea/assets/73806216/b7191c50-ca1f-462d-a79b-1fcde12fe877)

2023-12-28 22:46 UTC, BenjaTK commented
Btw, is there any way you could remove the files that don't need to be changed? Like project.godot, so only the files you changed stay.

2023-12-28 23:27 UTC, DaviD4Chirino commented
Yeah it should be posible, in this case project.godot is mostly static
except for the version

El jue., 28 de dic. de 2023 6:47 p. m., BenjaTK ***@***.***>
escribió:

> Btw, is there any way you could remove the files that don't need to be
> changed? Like project.godot, so only the files you changed stay.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BenjaTK/Gaea/pull/88#issuecomment-1871608367>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY6RG623OTM543DWRHA2IA3YLXZGLAVCNFSM6AAAAABBCLXU6OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZRGYYDQMZWG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-29 13:46 UTC, BenjaTK commented
This all looka great! Thank you so much! Merging rn.

2023-12-30 03:14 UTC, DaviD4Chirino commented
yeah its ready, also i saw your preview noise test and i tink i i can implement it, so when that is ready i will modify acordingly

pd: i only saw the first part of the last message, so thats why i took so long to answer

2023-12-30 18:44 UTC, merged

2023-12-30 18:44 UTC, BenjaTK commented
Thanks a lot for your contribution!